### ISSUE TITLE
Conflicts with android navigation jetpack library.

### ISSUE THREAD

**Issue by bobby-kim-km** [awslabs/aws-mobile-appsync-sdk-android#366] opened 2021-08-24 01:38 UTC
Issue occurs when using app-sync 3.2.0 and navigation 2.3.5 together.
During the build process, the code generated by app-sync results in two @Nullable.

ex> final @Nullable @Nullable List<AllAsset> allAssets;

If the app-sync 3.2.0 version and navigation 2.3.0-alpha04 version are used together, they work in a formal manner.

**Comment by IndianaSloan** [comment] 2021-10-19 06:59
FYI this is a duplicate of this issue - https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/273 that has been open for 18 months...

**Comment by eeatonaws** [comment] 2022-05-19 22:47
I apologize for the delay in responding. We are actively investigating the issue and working on a fix. Closing this issue as it is a duplicate of #273

**Closed by eeatonaws** 2022-05-19 22:47 UTC
Labels: bug, duplicate
