### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by STAR-ZERO** [awslabs/aws-mobile-appsync-sdk-android#323] opened 2020-11-24 03:19 UTC
**Is your feature request related to a problem? Please describe.**

I want to drop Jetifier because I want to improve build speed.
However, AppSync SDK uses old support libraries.
Please migrate to AndroidX.

**Describe the solution you'd like**

Please use AndroidX library instead of old support libraries.

**Describe alternatives you've considered**

I use Jetifier yet.

**Additional context**

For now, I use version 2.x because version 3.x has several issues with my application.
Therefore, I hope that not only version 3 but also version 2.x will be migrated to AndroidX.

**Comment by jamesonwilliams** [comment] 2020-11-30 05:59
Duplicate of https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/201

**Closed by jamesonwilliams** 2020-11-30 05:59 UTC
