### ISSUE TITLE
Gradle cannot sync: Unable to find method 'org.gradle.api.internal.file.DefaultSourceDirectorySet ...

### ISSUE THREAD

**Issue by RandomEngy** [awslabs/aws-mobile-appsync-sdk-android#307] opened 2020-08-12 23:01 UTC
**Describe the bug**
Gradle cannot sync with the `com.amazonaws.appsync` plugin

`Unable to find method 'org.gradle.api.internal.file.DefaultSourceDirectorySet.<init>(Ljava/lang/String;Ljava/lang/String;Lorg/gradle/api/internal/file/FileResolver;Lorg/gradle/api/internal/file/collections/DirectoryFileTreeFactory;)V'.`

**To Reproduce**
Android Gradle Plugin Version 4.0.1
Gradle Version 6.6
In project build.gradle:
dependency `classpath 'com.amazonaws:aws-android-sdk-appsync-gradle-plugin:3.0.1'`
In app build.gradle:
`apply plugin: 'com.amazonaws.appsync'` <- The gradle error points to this line
dependency  `implementation 'com.amazonaws:aws-android-sdk-appsync:3.1.0'`

**Expected behavior**
Gradle sync succeeds

**Environment:**
 - AppSync SDK Version: 3.1.0

**Comment by RandomEngy** [comment] 2020-08-13 15:48
Works with
Android Gradle Plugin Version 3.6.3
Gradle version 5.6.4

**Comment by jamesonwilliams** [comment] 2020-09-16 20:07
Duplicate of https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/270

Please use AppSync Gradle Plugins [3.1.0+](https://github.com/awslabs/aws-mobile-appsync-sdk-android/releases/tag/release_v3.1.0), or [2.11.0](https://github.com/awslabs/aws-mobile-appsync-sdk-android/releases/tag/release_v2.11.0).

**Closed by jamesonwilliams** 2020-09-16 20:07 UTC
Labels: AppSync, Bug

**Comment by RandomEngy** [comment] 2020-09-16 21:26
But I am already using v3.1.0 and it's not working.

**Comment by jamesonwilliams** [comment] 2020-09-16 21:32
> dependency classpath 'com.amazonaws:aws-android-sdk-appsync-gradle-plugin:3.0.1'

Please update this one -- this is the one that's causing the problem. 

https://github.com/awslabs/aws-mobile-appsync-sdk-android/releases/tag/release_v3.1.1

**Comment by RandomEngy** [comment] 2020-09-18 17:05
Ahh, thanks. Got those two mixed up. It's building fine now!
