### ISSUE TITLE
AppSync Gradle Plugin Not Compatible with Gradle 6

### ISSUE THREAD

**Issue by tonyyhliu** [awslabs/aws-mobile-appsync-sdk-android#270] opened 2020-04-17 03:11 UTC
When I add:
```
apply plugin: 'com.amazonaws.appsync' to my app's build.gradle
```

I get this error when I sync: 

```
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'com.amazonaws.appsync']
```

**Comment by murilodag** [comment] 2020-04-28 01:08
Hello @tonyyhliu , do you also have the message below?
If so, you need to downgrade the gradle from 6.x.x. to a 5.x.x version.
```
Could not create an instance of type com.apollographql.apollo.gradle.GraphQLSourceDirectorySet.
      > 'void org.gradle.api.internal.file.DefaultSourceDirectorySet.<init>(java.lang.String, java.lang.String, org.gradle.api.internal.file.FileResolver, org.gradle.api.internal.file.collections.DirectoryFileTreeFactory)'
```

The message above is easily reproducible after adding the plugin to an empty project and using gradle 6.x.x

**Comment by jamesonwilliams** [comment] 2020-04-28 01:30
Confirmed, I've run into this, too. This is a re-statement of https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/248, but the important variable is the Gradle version as noted in this https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/270.

**Comment by tonyyhliu** [comment] 2020-04-28 02:18
Thank you both. I've downgraded my gradle version to 5.x.x and it is working!

**Comment by murilodag** [comment] 2020-04-28 02:19
I am not sure why #248 or this one were closed. Gradle 6.0.0 is already in the Android Studio pipeline and it will be the default for many developers in a few months.

**Comment by tonyyhliu** [comment] 2020-04-28 02:30
Sorry, I'll reopn this one. I am a beginner at this and I thought if the issue is resolved, I should close.

**Comment by jamesonwilliams** [comment] 2020-04-28 06:15
@murilodag I had closed #248 because the poster had found a suitable workaround. At the time that ticket was raised, Android Studio 4 was still in _canary_ builds. The stable production version of Android Studio / Gradle Plugin is 3.6.3 as ot day and still defaults to Gradle 5.6.4. I agree with you that AppSync's Gradle 6.x incompatibility is gaining increasing urgency, though.

**Comment by mslagle-gd** [comment] 2020-05-28 21:38
Any updates here? 4.0 is now released.

**Comment by SolidScorpion** [comment] 2020-05-29 07:15
Really interested in this being resolved. Our team wants to update to AS4 to use new feature but at the same time AppSync is stopping us from this

**Comment by tonyyhliu** [comment] 2020-05-29 16:18
My issue has been resolved from downgrading the gradle. It may be closed.

**Comment by Mzuraiqi** [comment] 2020-05-31 13:25
I had the same issue, when I updated Android Studio to version 4.0, I got the above mentioned error, as the AS4.0 uses Plugin version 4.0.0 and Gradle version 6.1.1.

The issue is solved by downgrading the plugin version to 3.6.2 and gradle version to 5.6.4, however, Android studio keeps recommending updating Android gradle plugin for best performance and to use the new features.

I downgraded the gradle settings by going to  File > Project Structure > Project

**Comment by MujammilAhamed** [comment] 2020-06-01 10:26
I have also faced the same issue

**Comment by yusufa2z** [comment] 2020-06-01 18:03
Android Studio 4 is now released.

**Comment by jibreel** [comment] 2020-06-01 19:27
Android devs working with AppSync should be able to use the plugin with the currently released version of Android Studio and it's recommended Gradle versions. I have temporarily downgraded to Version 5.X, but will need to go enable version 6.0 in the future.

**Comment by vlazdra** [comment] 2020-06-09 07:20
Is anyone from the development team aware of this ? It's been 6 months since Gradle 6.0 and Android Canary 1 with the AGP 4.0 were released.
While downgrading is a temporary fix, we can't use the latest improvments and tools because of this blocker.
It's a shame that such a huge company can't fix this faster.

**Comment by murilodag** [comment] 2020-06-09 12:45
Hello @vlazdra, I tried contacting the assigned developer (@desokroshan), but no answer so far.

**Comment by Crisp3333** [comment] 2020-06-09 15:47
Downgrading gradle version does not work for me. The only option is to downgrade from Android Studio 4.0.

**Comment by vlazdra** [comment] 2020-06-09 16:18
> Downgrading gradle version does not work for me. The only option is to downgrade from Android Studio 4.0. I am unable to work on my project for over a week now.

You can still use Android Studio 4.0, but you will need to downgrade the Android Gradle Plugin in the project level build.gradle file to 3.6.2

**Comment by jamesonwilliams** [comment] 2020-06-09 17:13
This issue is one of several related issues, regarding the architecture of the AppSync SDK.

This AppSync codebase originated as a fork of the Apollo codebase. The original commits entered this repository as copy-paste of the Apollo code, discarding that project’s git history. As a result, I have only a general idea of when the fork occurred, with respect to Apollo’s commit hashes and release tags. This makes it challenging to maintain the repository, as the upstream codebase evolves.

The best possible solution to this current issue would be to take a dependency on Apollo, instead of cloning it. Or, even just to merge in Apollo’s updates, to this codebase. This way, we’d get the upstream Gradle fixes without needing to re-inventing them. This solution is one around repository maintenance, as opposed to finding deliberate Gradle changed.

Another possible solution would be to fix the Gradle incompatibility directly, further drifting from the Apollo codebase. I assume this is the less costly of the two options, in the short term. I’ve sat down to complete this task a couple of times, but got pulled away to other things before I could complete it.

Unfortunately, I do not think it is possible to “re-up” the plugin from the Apollo source, independently from the other Apollo modules. The plugin has a versioned contract with the other modules, that would break, if they aren’t all updated together.

All of this said, this issue is quickly garnering reactions, and becoming one of our more visible. I will bring it back to my team to assess prioritization. My explanation above is for visibility: we are aware of this issue, and are discussing it. I hope that my explanation of the situation helps maintain your trust.

I appreciate your patience. For the immediate time-being, I do recommend the workaround of using [AGP 3.6.3](https://mvnrepository.com/artifact/com.android.tools.build/gradle/3.6.3) (the last stable release before 4) and Gradle 5.6.4. You can use Android Studio 4; these are project-specific configurations.

**Comment by murilodag** [comment] 2020-06-09 17:34
Thanks @jamesonwilliams. My team appreciates the visibility and we are currently working with the proposed workaround.

We also understand breaking changes are normal, they will continue to happen and the short term solution might not be the best overall.

The only item pending is estimates for fixes and release. You might not have those yet and it is fine. Let us know when you do.

**Comment by GoranCDiscovery** [comment] 2020-06-16 15:50
Jesus Amazon..  It's been 2 months since this issue was raised. Pull yourself together!!

**Comment by hakobt** [comment] 2020-06-19 10:18
Hello, any news on this issue ?

Also, will the fix be released on version 2.x too or only 3.x ?

**Comment by murilodag** [comment] 2020-06-25 01:37
Hello @jamesonwilliams, it is been over two weeks from your last message.

Do you have any other information on the current progress?

**Comment by jpignata** [comment] 2020-06-25 01:46
Hi @murilodag  -- this is on our backlog and will be in our next release. Thanks.

**Comment by ahardin** [comment] 2020-06-25 03:21
Not that this is the venue for whining and complaining, but frankly it's fairly frustrating that AWS oversells so many of their services/offerings and then leaves it on their developers to hack together solutions in order to deliver the goods. It's then exacerbated by the oft-felt impression that there are like 1 or 2 developers working on some of these libraries.

**Comment by jpignata** [comment] 2020-06-25 12:24
> Not that this is the venue for whining and complaining

@ahardin Please feel free to email me or contact me on Discord. Happy to figure out how we can help you with any specific issues, and would like to hear more.

**Comment by SunnyBe** [comment] 2020-07-08 00:31
I am using Gradle 6.5.1 and build tool `4.1.0-beta01` and I am having an issue with AWS AppSync, any fix yet?

**Comment by bbb-levin** [comment] 2020-07-08 09:58
I'm using gradle 5.6.4 android build tool 3.6.3 and I'm still build faild.

I using appsync for aws modile sdk, using plugin "com.amazonaws.appsync",

and using kotlin, kotlin-ktx, androidx core, compat, lifecycle dependencies.

I was try to build, I saw below message.

string too large to encode using UTF-8 written instead as 'STRING_TOO_LARGE'.


What's wrong?

**Comment by jamesonwilliams** [comment] 2020-07-15 19:43
I hacked some more on @jpignata's https://github.com/awslabs/aws-mobile-appsync-sdk-android/pull/301, and was able to get the plugin generating code again, with a Gradle 6.1.1 project / Android Gradle Plugin 4.0.0.

Let me know if you'd like to test it out, pre-release. Otherwise, should be going out next release (3.1.0.)

**Comment by mohamed-khaled-hsn** [comment] 2020-07-15 19:46
Please consider release also for who are still using v2 and can't migrate to Appsync v3

**Comment by vlazdra** [comment] 2020-07-15 20:04
> I hacked some more on @jpignata's https://github.com/awslabs/aws-mobile-appsync-sdk-android/pull/301, and was able to get the plugin generating code again, with a project using Gradle 6.1.1 / Android Gradle Plugin 4.0.0.
> 
> Let me know if you'd like to test it out, pre-release. Otherwise, should be going out next release (3.1.0.)

That's great to hear.
Do you have any ETA on when will the 3.1.0 hit stable and be available for us to pull in to our production apps?

**Comment by ahardin** [comment] 2020-07-15 21:21
> I hacked some more on @jpignata's #301, and was able to get the plugin generating code again, with a project using Gradle 6.1.1 / Android Gradle Plugin 4.0.0.
> 
> Let me know if you'd like to test it out, pre-release. Otherwise, should be going out next release (3.1.0.)

I'd be happy to test out a pre-release, but it occurred to me that I'm already running a custom fork in order to deal with PR #199 / issue #116. If that PR could also be merged I'd be happy to test this out.

**Comment by jamesonwilliams** [comment] 2020-07-16 21:49
I have just released the fix in version 3.1.0.

https://github.com/awslabs/aws-mobile-appsync-sdk-android/releases/tag/release_v3.1.0

Will work on backporting to 2.x. Closing this issue for now.

@ahardin Let's deal with #116 / #199 as separate concerns.

**Closed by jamesonwilliams** 2020-07-16 21:49 UTC

**Comment by jamesonwilliams** [comment] 2020-07-20 19:09
@mohamed-khaled-hsn I just released this into 2.11.0.

https://github.com/awslabs/aws-mobile-appsync-sdk-android/releases/tag/release_v2.11.0

**Comment by oras** [comment] 2020-10-18 06:10
Hi James, thanks for your replay

My Android Studio version info: 

Android Studio 4.1
Build #AI-201.8743.12.41.6858069, built on September 23, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.new.welcome.screen.force=true, debugger.watches.in.variables=false, cidr.max.intellisense.file.length=1400000
Non-Bundled Plugins: com.thoughtworks.gauge, com.intellij.lang.jsgraphql, org.intellij.plugins.markdown, name.kropp.intellij.makefile, BashSupport, org.siprop.android.opencl.OpenCLCLGenerator, PythonCore, aws.toolkit

Gradle version 6.7
Gradle plugin 4.2.0-alpha13

Gradle error trace:

A problem occurred configuring root project 'DOV'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.github.node-gradle:gradle-node-plugin:2.2.4.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/node-gradle/gradle-node-plugin/2.2.4/gradle-node-plugin-2.2.4.pom
       - https://jcenter.bintray.com/com/github/node-gradle/gradle-node-plugin/2.2.4/gradle-node-plugin-2.2.4.pom
     Required by:
         project : > com.amazonaws:aws-android-sdk-appsync-gradle-plugin:3.1.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by jamesonwilliams** [comment] 2020-10-19 17:20
Hi @oras The error you're getting doesn't have the same signature. Please open a new/separate GitHub issue for it.
